config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#top"
  get '/about' => "homes#about"
  resources :posts
  resources :users, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  attachment :image
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :realize, :think, :understand, :question )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introdution)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>

app/views/homes/top.html.erb
<h1>Homes#top</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nande</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li>
              <%= link_to 'マイページ', user_path(current_user.id) %>
            </li>
            <li>
              <%= link_to 'ユーザー一覧', users_path %>
            </li>
            <li>
              <%= link_to '投稿一覧', posts_path %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li>
              <%= link_to '投稿フォーム', new_post_path %>
            </li>
          <% else %>
            <li>
              <%= link_to '投稿一覧', posts_path %>
            </li>
            <li>
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
            <li>
              <%= link_to "ログイン", new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, local:true do |f| %>
  <div class="field">
    <%= f.label :title do %>
      <ruby>不思議<rt>ふしぎ</rt></ruby>に<ruby>思<rt>おも</rt>ったこと
    <% end %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image do %>
      <ruby>写真<rt>しゃしん</rt>
    <% end %><br>
    <%= f.attachment_field :image %>
  </div>
  <div class="field">
    <%= f.label :realize do %>
      <ruby>気付<rt>きづ</rt>いたこと
    <% end %><br>
    <%= f.text_area :realize %>
  </div>
  <div class="field">
    <%= f.label :think do %>
      <ruby>思<rt>おも</rt>ったこと
    <% end %><br>
    <%= f.text_area :think %>
  </div>
  <div class="field">
    <%= f.label :understand do %>
      <ruby>分<rt>わ</rt>かったこと
    <% end %><br>
    <%= f.text_area :understand %>
  </div>
  <div class="field">
    <%= f.label :question do %>
      まだ<ruby>分<rt>わ</rt>からないこと
    <% end %><br>
    <%= f.text_area :question%>
  </div>
  <%= f.submit 'できた！' %>
<% end %>

app/views/posts/edit.html.erb
<h1>へんフォーム</h1>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div>
  <%= attachment_image_tag post, :image, size: "500x350" %>
  <%= link_to  post.title, post_path(post) %>
  <p>ユーザーネーム：<%= post.user.name %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<h1>投稿フォーム</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="post-show">
  <h3><%= @post.title %></h3>
  <%= attachment_image_tag @post, :image, size: "500x350" %>
  <h4>ユーザーネーム：<%= @post.user.name %></h4>
  <div>
    <h4><ruby>気付<rt>きづ</rt>いたこと</h4>
    <p><%= @post.realize %></p>
  </div>
  <div>
    <h4><ruby>思<rt>おも</rt>ったこと</h4>
    <p><%= @post.think %></p>
  </div>
  <div>
    <h4><ruby>分<rt>わ</rt>かったこと</h4>
    <p><%= @post.understand %></p>
  </div>
  <div>
    <h4>まだ<ruby>分<rt>わ</rt>からないこと</h4>
    <p><%= @post.question %></p>
  </div>
  <h4>投稿日時：<%= @post.created_at.strftime('%Y/%m/%d') %></h4>
  <% if @post.user == current_user %>
    <%= link_to "編集", edit_post_path(@post) %>
    <%= link_to "削除", post_path(@post), method: :delete %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model:@user, local:true do |f| %>
  <div class="field">
    <%= f.label :name do %>
      <ruby>名前<rt>なまえ</rt>
    <% end %><br>
    <%= f.text_field :name %>
  </div>
  <%= attachment_image_tag @user, :profile_image, size: "100x100" %>
  <div class="field">
    <%= f.label :profile_image do %>
      <ruby>画像<rt>がぞう</rt>
    <% end %><br>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  </div>
  <div class="field">
    <%= f.label :introdution do %>
      <ruby>自己紹介<rt>じこしょうかい</rt>
    <% end %><br>
    <%= f.text_field :introdution %>
  </div>
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <div>
    <p>ユーザーネーム：<%= user.name %></p>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %>のページ</h3>
  <%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg' %><br>
  <p><ruby>自己紹介<rt>じこしょうかい</rt></p>
  <p><%= @user.introdution %></p>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>
<% if @posts.present? %>
  <% @posts.each do |post| %>
  <div>
    <%= attachment_image_tag post, :image, size: "500x350" %><br>
    <%= link_to  post.title, post_path(post) %>
    <p>ユーザーネーム：<%= post.user.name %></p>
  </div>
  <% end %>
<% else %>
  <p>まだなんで<ruby>記事<rt>きじ</rt>はありません</p>
  <% if @user == current_user %>
    <%= link_to new_post_path do %>
      なんで<ruby>記事<rt>きじ</rt>を<ruby>書<rt>か</rt>く！
    <% end %>
  <% end %>
<% end %>